import Head from 'next/head'
import Image from 'next/image'
import home from '../styles/Home.module.css'
import Header from '../components/Header.js'
import Work1 from '../images/work1.png'
import Work2 from '../images/work2.png'
import Work3 from '../images/work3.png'
import Work4 from '../images/work4.png'
import Work5 from '../images/work5.png'
import Skill from '../images/skill.png'

import Footer from '../components/Footer.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vignesh Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
       
        
        
      </Head>


      <Header></Header>

      <section className='position-relative p-0'>
      <div className={home.circle_g_bg}></div>
      <div className={home.circle_y_bg}></div>
        <div className="container-fluid">
          <div className="row align-items-center justify-content-center">
            <div className="col-lg-12">
            <div className={home.mainbanner}>
              <div className="ban-text">
              <h2>Hi</h2>
                <h2>I am</h2>
                <h1>VIGNESH <br/> <span className='text-dark'>IYER</span></h1>
                <p>Web Designer & Developer </p>
              </div>
              <div className={home.ban_cta}>
                <div className={home.ban_social}>
                  <ul>
                    <li><a href="https://www.facebook.com/artist.VigneshVenkatraman" target="_blank"><i className="feather icon-feather-facebook"></i></a></li>
                    <li><a href="https://www.instagram.com/viggy_i/" target="_blank"><i className="feather icon-feather-instagram"></i></a></li>
                    <li><a href="https://www.linkedin.com/in/vignesh-iyer-41249279/" target="_blank"><i className="feather icon-feather-linkedin"></i></a></li>
                  </ul>
                </div>
                <div className={home.shortwork}>
                  <a href="#work">
                    <div className={home.banbtn}>
                      <i className="feather icon-feather-arrow-down"></i>
                      <span>WORK</span>
                    </div>
                  </a>
                </div>
              </div>
           
            </div>
               
            </div>
          </div>
        </div>
      </section>

      <section className='position-relative' id='about'>
          <div className={home.circle_about_g}></div>
          <div className="container">
            <div className="row align-items-center">
              <div className="col-lg-5 col-md-6">
                  <div className={home.about_title}>
                    <h3>ABOUT ME</h3>
                  </div>
              </div>
              <div className="col-lg-7 col-md-6">
                    <p>I am Professional Web Designer & Developer, who has 5 years of Experience, had 
an Exciting Journey till now, Worked with Several Organizations & Understand the 
Concepts & Requirement in Depth. Enjoyed & Willing to Enjoy more Challenges.</p>

<p>My Ultimate Goal to provide a best Services & seek to learn more from it </p>
              </div>
            </div>
          </div>
      </section>

      <section id='experience'>
        <div className="container">
          <div className="row align-items-center justify-content-center col-rev-m">
              <div className="col-lg-5 col-md-6">
                <div className={home.exp_det}>
                  <div className={home.exp}>
                    <p><span className={home.exp_dur}>2020-2022 </span>Worked at</p>
                    <p className={home.company}>FIVE ONLINE WEB SOLUTIONS</p>
                    <p className={home.desig}>as UI/ UX Designer</p>
                  </div>
                  <div className={home.exp}>
                    <p><span className={home.exp_dur}>2020-2022 </span>Worked at</p>
                    <p className={home.company}>FIVE ONLINE WEB SOLUTIONS</p>
                    <p className={home.desig}>as UI/ UX Designer</p>
                  </div>
                  <div className={home.exp}>
                    <p><span className={home.exp_dur}>2020-2022 </span>Worked at</p>
                    <p className={home.company}>FIVE ONLINE WEB SOLUTIONS</p>
                    <p className={home.desig}>as UI/ UX Designer</p>
                  </div>
                </div>
              </div>
              <div className="col-lg-5 col-md-6">
                  <h3 className={home.exp_title}>WORK<br /> EXPERI<br />ENCE</h3>
              </div>
          </div>
        </div>
      </section>

      <section id="work">
        <div className="container">
          <div className="row justify-content-center align-items-center">
            <div className="col-lg-12">
              <div className={home.work_title}>
                <h3>Work <br/> Highlights</h3>
              </div>
            </div>
            <div className="col-lg-4 col-md-5 text-center m-30-tb">
            <a href="https://fiveonlineclient.in/sejalglasses/" target="_blank" className="work-link">
              <div className={home.work_image}>
                
                    <Image 
                      src={Work1}
                      alt="Work"
                      className={home.work_img}
                    />
                  
              </div>
              <h6 className='text-center'>Sejal Glass</h6>
              </a>
            </div>
            <div className="col-lg-4 col-md-5 text-center m-30-tb">
            <a href="https://sunstellar.in/" target="_blank" className="work-link">
            <div className={home.work_image}>
                  
                    <Image 
                      src={Work2}
                      alt="Work"
                      className={home.work_img}
                    />
                 
              </div>
              <h6 className='text-center'>Sunstellar</h6>
              </a>
            </div>
            <div className="col-lg-4 col-md-5 text-center m-30-tb">
            <a href="https://fiveonlineclient.in/arihant" target="_blank" className="work-link">
            <div className={home.work_image}>
                  
                    <Image 
                      src={Work3}
                      alt="Work"
                      className={home.work_img}
                    />
                  
              </div>
              <h6 className='text-center'>Arihant Electricals</h6>
              </a>
            </div>
            <div className="col-lg-4 col-md-5 text-center m-30-tb">
            <a href="https://eb5an.in/" target="_blank" className="work-link">
            <div className={home.work_image}>
                  
                    <Image 
                      src={Work5}
                      alt="Work"
                      className={home.work_img}
                    />
                  
              </div>
              <h6 className='text-center'>EBAN</h6>
              </a>
            </div>
            <div className="col-lg-4 col-md-5 text-center m-30-tb">
            <a href="http://mit-worldwide.com/" target="_blank" className="work-link">
            <div className={home.work_image}>
                  
                    <Image 
                      src={Work4}
                      alt="Work"
                      className={home.work_img}
                    />
                  
              </div>
              <h6 className='text-center'>MIT Worldwide</h6>
              </a>
            </div>
            
          </div>
        </div>
      </section>

      <section className="position-relative" id='skills'>
        <div className={home.circle_skill_y}></div>
        <div className="container">
          <div className="row">
            <div className="col-lg-8">
              <div className={home.skill_title}>
                <h3>TECHNICAL SKILLS</h3>
              </div>
              <Image 
                      src={Skill}
                      alt="Work"
                      className={home.skill_img}
                    />
            </div>
          </div>
        </div>
      </section>

      <section className='position-relative' id='blogs'>
     
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-12">
            <div className={home.about_title}>
                    <h3>BLOGS</h3>
                  </div>
            </div>

            <div className="coming-soon">
              <h2>COMING SOON</h2>
            </div>
          </div>
        </div>
      </section>

      <section className='position-relative'>
      <div className={home.circle_about_g}></div>
      <div className="container">
      <div className="row">
        <div className="col-lg-12">
            <div className={home.contact_title}>
                    <h3>FEEL FREE <br />TO CONTACT</h3>
            </div>

            <div className={home.contact}>
                <i className='feather icon-feather-phone'></i>
                <a href="tel: +918356068719">+91-8356068719</a>
            </div>
            <div className={home.contact}>
                <i className='feather icon-feather-mail'></i>
                <a href="mailto: vigeshiyer212@gmail.com">vigeshiyer212@gmail.com</a>
            </div>
        </div>
        </div>
      </div>
        
      </section>

      <Footer></Footer>

    </>
  )
}
